(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const params=new URLSearchParams(location.search),taskId=params.get('task_id')||'WO-HYD-2026-0828-017';
  let data=null,toastTimer;
  if(params.get('embed')==='1')document.body.classList.add('embedded');
  if(params.get('view')==='expert-feed')document.body.classList.add('expert-feed');
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Demo-Role':'operator','X-Demo-Actor':encodeURIComponent('赵工/A045'),...options.headers}});const payload=await response.json();if(!response.ok)throw new Error(payload.error||`接口错误 ${response.status}`);return payload;}
  function toast(message,kind=''){const el=$('terminalToast');el.textContent=message;el.className=`terminal-toast show ${kind}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='terminal-toast',2800);}
  function statusLabel(status){return {draft:'等待下发',running:'执行中',paused:'异常暂停',pending:'待领取',completed:'整架已完工'}[status]||status;}
  async function refresh(){try{data=await api(`/api/bootstrap?task_id=${encodeURIComponent(taskId)}`);render();}catch(error){toast(error.message,'danger');}}
  function render(){
    const task=data.task,device=data.device,step=task.steps[task.current_step-1]||task.steps.at(-1),executable=['running','paused'].includes(task.status),requiresPart=task.current_step<=6;
    text('terminalId',`${device.id} · ${device.name}`);text('terminalBattery',`${device.battery}%`);text('terminalTask',task.id);text('terminalProduct',`${task.product} / ${task.station}`);text('terminalOperator',task.operator);text('terminalProgress',`${task.current_step} / ${task.steps.length}`);text('terminalStatus',statusLabel(task.status));
    $('terminalStepList').innerHTML=task.steps.map(item=>`<li class="${item.status==='completed'?'done':''} ${item.step_no===task.current_step?'current':''}"><strong>${item.step_no}. ${esc(item.title)}</strong><span>${item.status==='completed'?'已确认':item.step_no===task.current_step?'当前工序':'待执行'}</span></li>`).join('');
    text('terminalStepCode',`主要工序 ${String(step.step_no).padStart(2,'0')} / ${String(task.steps.length).padStart(2,'0')}`);text('terminalStepTitle',task.status==='draft'?'等待管理端下发工单':task.status==='pending'?'扫描工单码领取作业':task.status==='completed'?'整架装配已完成':step.title);text('terminalInstruction',task.status==='draft'?'工单草稿尚未发送到现场AR终端。':task.status==='pending'?`识别工单 ${task.id}，核对架次、工位和工艺版本后领取。`:task.status==='completed'?'八个主要工序均已确认，全过程数据已归档。':step.instruction);text('terminalParameter',step.parameter);text('terminalSafety',step.safety);text('terminalObject',step.title);text('terminalObjectStatus',`工单 ${task.id} · 内容包 ${task.process_version} 已匹配`);
    $('terminalClaim').hidden=!['draft','pending'].includes(task.status);$('terminalClaim').disabled=task.status==='draft';$('terminalClaim').textContent=task.status==='draft'?'等待管理端下发':'扫描工单码并领取';$('captureActions').hidden=!executable;$('terminalScan').hidden=!requiresPart;$('terminalConfirm').disabled=task.status!=='running';$('terminalPause').disabled=!executable;$('terminalPause').textContent=task.status==='paused'?'恢复当前工单':'暂停当前工单';$('terminalBack').disabled=!executable||task.current_step<=1;$('terminalAi').disabled=!executable;$('terminalMaintenance').disabled=!executable;$('terminalIncident').disabled=task.status!=='running';$('terminalCheck').parentElement.hidden=!executable;$('terminalCheck').checked=false;
    const currentIdentifications=(data.partIdentifications||[]).filter(item=>item.step_no===task.current_step),latestPart=currentIdentifications.at(-1),matched=currentIdentifications.some(item=>item.result==='matched');
    $('terminalPartStatus').hidden=!executable||!requiresPart;$('terminalPartStatus').className=`terminal-part-status ${matched?'matched':latestPart?.result==='blocked'?'blocked':latestPart?.result==='needs_review'?'review':''}`;
    $('terminalPartStatus').innerHTML=matched?`<strong>零部件校验通过</strong><span>${esc(currentIdentifications.find(item=>item.result==='matched').component)} · 型号、工单、工序及BOM一致</span>`:latestPart?`<strong>${latestPart.result==='blocked'?'错误零部件已拦截':'需要人工复核'}</strong><span>${esc(latestPart.message)}</span>`:'当前工序尚未完成零部件编码校验';
    const latestObservation=(data.observations||[]).at(-1);$('terminalCaptureResult').hidden=!executable;$('terminalCaptureResult').innerHTML=latestObservation?`<strong>${esc(latestObservation.label)}</strong><span>${esc(latestObservation.value)}</span><small>已写入平台 · 主要工序 ${latestObservation.step_no}</small>`:'尚无本工单现场采集记录';
    const session=data.sessions.find(item=>item.status==='active'),annotations=session?.annotations||[],latest=annotations.at(-1);$('expertOverlay').hidden=!latest;if(latest)text('expertOverlayText',latest.payload.text);
    dispatchEvent(new CustomEvent('ar-stage-changed',{detail:{stage:step.step_no,media:step.media}}));
  }
  function text(id,value){const el=$(id);if(el)el.textContent=value;}
  async function claimWorkOrder(){try{await api(`/api/tasks/${data.task.id}/claim`,{method:'POST',body:JSON.stringify({operator:'赵工/A045',device_id:data.device.id})});await refresh();toast('工单已领取，八个主要工序和受控内容已同步。');}catch(error){toast(error.message,'danger');}}
  function captureDescriptor(){const stage=data.task.current_step,names={1:'主要结构件',2:'底座与连杆',3:'掩护梁与顶梁',4:'立柱与千斤顶',5:'推移机构',6:'操纵阀组与胶管',7:'功能试验',8:'完工复检'},name=names[stage]||'装配对象';return{kind:'photo',label:`${name}现场照片`,value:`IMG-${Date.now()} · 1280×720 · 已上传`,media_ref:'/assets/ar-feed.png'};}
  async function capture(){const task=data.task,descriptor=captureDescriptor();try{await api(`/api/tasks/${task.id}/observations`,{method:'POST',body:JSON.stringify({...descriptor,step_no:task.current_step,device_id:data.device.id})});await refresh();toast('现场照片已上传并同步到管理端。');}catch(error){toast(error.message,'danger');}}
  function scenarioCode(){const task=data.task,stage=task.current_step,family=(task.model.match(/ZZ\d{2}/)||['ZZ18'])[0],order=task.id.slice(-3),scenario=$('partScenario').value;return scenario==='wrong-model'?`PART-ZZ16-S${String(stage).padStart(2,'0')}-${order}`:scenario==='wrong-order'?`PART-${family}-S${String(stage).padStart(2,'0')}-${order==='018'?'017':'018'}`:scenario==='wrong-step'?`PART-${family}-S${String(stage===6?2:6).padStart(2,'0')}-${order}`:scenario==='unreadable'?'CODE-***-UNREADABLE':`PART-${family}-S${String(stage).padStart(2,'0')}-${order}`;}
  function openPartScan(){$('partScenario').value='match';$('partCodeInput').value=scenarioCode();$('partScanResult').className='part-scan-result';$('partScanResult').textContent='系统将校验产品型号、装配工单、当前工序和BOM关系。';$('partScanDialog').showModal();}
  async function identifyPart(event){if(event.submitter?.value==='cancel')return;event.preventDefault();$('partScanResult').textContent='正在解析编码并执行业务校验...';try{const result=await api(`/api/tasks/${data.task.id}/parts/identify`,{method:'POST',body:JSON.stringify({code:$('partCodeInput').value,step_no:data.task.current_step,device_id:data.device.id})}),item=result.identification,labels={matched:'匹配通过',needs_review:'人工复核',blocked:'错误拦截'},checks=[['产品型号',item.checks.model],['装配工单',item.checks.work_order],['当前工序',item.checks.process],['BOM关系',item.checks.bom]];$('partScanResult').className=`part-scan-result ${item.result==='needs_review'?'review':item.result}`;$('partScanResult').innerHTML=`<div class="part-result-head"><strong>${esc(item.component)}</strong><em>${labels[item.result]}</em></div><div class="part-check-grid">${checks.map(([label,pass])=>`<span class="${pass?'':'fail'}">${label}<br>${pass?'通过':'不通过'}</span>`).join('')}</div><p>${esc(item.message)}</p><small>${esc(item.raw_code)} · ${esc(item.bom_item)}</small>`;await refresh();toast(item.result==='matched'?'零部件匹配通过，可以继续装配。':item.result==='blocked'?'错误零部件已拦截。':'编码需要人工复核。',item.result==='matched'?'':'danger');}catch(error){$('partScanResult').textContent=error.message;}}
  async function confirmProcess(){const task=data.task;if(task.current_step<=6&&!data.partIdentifications.some(item=>item.step_no===task.current_step&&item.result==='matched'))return toast('当前工序必须先完成零部件编码校验。','danger');if(!$('terminalCheck').checked)return toast('请先完成必要步骤并核对现场状态。');try{await api(`/api/tasks/${task.id}/steps/${task.current_step}/confirm`,{method:'POST',body:'{}',headers:{'Idempotency-Key':`ar-${task.id}-${task.current_step}-${Date.now()}`}});await refresh();toast(data.task.status==='completed'?'整架装配已完工并归档。':'主要工序已确认，管理端进度已同步。');}catch(error){toast(error.message,'danger');}}
  async function workOrderAction(action){try{await api(`/api/tasks/${data.task.id}/action`,{method:'POST',body:JSON.stringify({action})});await refresh();toast(action==='pause'?'当前工单已暂停。':'工单状态已更新。');}catch(error){toast(error.message,'danger');}}
  async function askKnowledge(event){if(event.submitter?.value==='cancel')return;event.preventDefault();text('terminalAiResult','正在检索企业知识库...');try{const result=await api('/api/ai/ask',{method:'POST',body:JSON.stringify({task_id:data.task.id,question:$('terminalAiInput').value,step_no:data.task.current_step})});$('terminalAiResult').innerHTML=`<strong>${esc(result.answer)}</strong><br><small>${result.citations?.length?'来源：'+result.citations.map(item=>`${esc(item.title)} ${esc(item.section)}`).join('；'):'资料不足，未返回引用'} · ${result.degraded?'本地演示':'企业知识服务'}</small>`;await refresh();}catch(error){text('terminalAiResult',error.message);}}
  async function queryMaintenance(event){if(event.submitter?.value==='cancel')return;event.preventDefault();text('terminalMaintenanceResult','正在查询相似案例...');try{const result=await api(`/api/maintenance/cases?q=${encodeURIComponent($('terminalMaintenanceInput').value.trim())}`);$('terminalMaintenanceResult').innerHTML=result.items.length?result.items.slice(0,3).map(item=>`<strong>${esc(item.component)} · ${esc(item.symptom)}</strong><br>${esc(item.resolution)}<br><small>原因：${esc(item.cause)} · 备件：${esc(item.parts)}</small><hr>`).join(''):'未找到相似案例，请转工艺负责人或远程专家。';}catch(error){text('terminalMaintenanceResult',error.message);}}
  async function submitIncident(event){if(event.submitter?.value==='cancel')return;event.preventDefault();try{await api('/api/incidents',{method:'POST',body:JSON.stringify({task_id:data.task.id,type:$('terminalIncidentType').value,description:$('terminalIncidentDescription').value,step_no:data.task.current_step}),headers:{'Idempotency-Key':`ar-incident-${Date.now()}`}});$('terminalIncidentDialog').close();await refresh();toast('异常已上报，当前工单暂停并通知远程专家。','danger');}catch(error){toast(error.message,'danger');}}

  $('terminalClaim').onclick=claimWorkOrder;$('terminalScan').onclick=openPartScan;$('terminalPhoto').onclick=capture;$('terminalConfirm').onclick=confirmProcess;$('terminalPause').onclick=()=>workOrderAction(data.task.status==='paused'?'resume':'pause');$('terminalBack').onclick=()=>workOrderAction('back');$('terminalAi').onclick=()=>$('aiDialog').showModal();$('terminalMaintenance').onclick=()=>$('terminalMaintenanceDialog').showModal();$('terminalIncident').onclick=()=>$('terminalIncidentDialog').showModal();$('terminalAiForm').onsubmit=askKnowledge;$('terminalMaintenanceForm').onsubmit=queryMaintenance;$('terminalIncidentForm').onsubmit=submitIncident;$('partScanForm').onsubmit=identifyPart;$('partScenario').onchange=()=>{$('partCodeInput').value=scenarioCode();};
  setInterval(()=>text('terminalClock',new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})),1000);setInterval(refresh,5000);refresh();
})();
